#name = input("enter your name ")
#email = input("enter your email ")
#address = input("enter your address ")
#phone = input ("enter your phone ")
#print(name, email, address, phone)
#print(f"My name is {name}. my email is{email}. my address is {address}. my phone number is {phone}")
#print(f"name: {name} \n address: {address}")
#principal = int(input("enter principal "))
#"time = int(input("enter time "))
#rate = int(input("enter rate "))
#print((rate*time*principal)/100)
#a, b, c = input("enter three numbers").split(",")
#print(a, b, c )
#name = input("enter your name ")
#email = input("enter your email ")
#address = input("enter your address ")
#print(f"My name is {name}, email address {email} and phone number is ram {address}")
#p = int(input("enter first number "))
#a = int(input("enter second number "))
#print(a+p)
#a, b, c = input("enter three numbers ").split(" ")
#print (a, b, c)
name = input("enter name ")
email = input("enter email ")
print(f"name is {name} \nemail is{email}")
